Remove comments from PR
NCATS-Gamma/robokop-rewrite pull request #121
Opened 2020-12-02 17:12 UTC by alongreyber

2020-12-02 19:15 UTC, maximusunc requested changes
Please remove all artifact logic from this PR. This should only be to remove bot comments.

2020-12-02 22:08 UTC, maximusunc requested changes
Are the github workflow main changes for the docker registry? And please remove all changes from package.json.

2020-12-03 14:24 UTC, alongreyber commented
Yes, the main.yml changes are to fix the push to the docker registry.

2020-12-03 15:51 UTC, maximusunc approved these changes

2020-12-03 15:54 UTC, merged