Split query-dispatcher into separate service
NCATS-Gamma/robokop-rewrite pull request #132
Opened 2020-12-10 20:11 UTC by alongreyber

2020-12-10 23:10 UTC, maximusunc requested changes

2020-12-11 16:30 UTC, alongreyber commented on frontend/package.json
> +    "hot-reload": "HOT_RELOAD=true webpack-dev-server --watch --config webpack.dev.js",
Are you sure that changes aren't reflected with hot reload? It's working for me. I've been testing it by changing some text on the page and it works fine.

Also - it seems like the page should automatically reload when there are code changes without the hotReload flag. It seems unproductive to look at a page that is running an outdated version of the code. Let me know if I'm missing something.

2020-12-11 18:18 UTC, maximusunc commented on frontend/package.json
> +    "hot-reload": "HOT_RELOAD=true webpack-dev-server --watch --config webpack.dev.js",
I can go in and try it again, but yeah, I made a change to some text but didn't see any change in the browser.

I agree that the reload is a feature. My personal preference is for it to not automatically reload. I don't want it to auto-reload if I'm asking a long-running question or on any other pages with a lot of state that I don't want to lose.

So can we please remove the auto-reload when not in hot-reload? But webpack should still watch for changes and auto-update the bundle that will be reflected the next time I manually refresh.

2020-12-11 18:22 UTC, maximusunc commented on frontend/package.json
> +    "hot-reload": "HOT_RELOAD=true webpack-dev-server --watch --config webpack.dev.js",
I get the hot reload working now, so that's fine.

2020-12-11 19:45 UTC, maximusunc approved these changes

2020-12-11 19:47 UTC, merged