Fix result table render
NCATS-Gamma/robokop-rewrite pull request #48
Opened 2020-10-15 17:59 UTC by maximusunc

Fixes issue #26. The useMessageStore was initially designed to only handle one answer and was hard to watch for message changes. This converts the message from a static ref to a useState where components like the ResultsTable can watch for any changes in the message and update accordingly.

2020-10-16 16:05 UTC, alongreyber requested changes

2020-10-16 16:05 UTC, alongreyber commented on src/stores/useMessageStore.js
> +  function toIndMap(arr) {
What is ind? Index? I think you should either use the full name, or add some kind of documentation explaining what this is.

2020-10-20 16:16 UTC, maximusunc commented on src/components/shared/answersetView/resultsTable/ResultsTable.jsx
> +      window.alert('We were able to retrieve the answers to this question. However, it seems there was an error retrieving some of the nodes. If you would like complete answers, please try asking thi
Switched this over to an alert, because the page can still be displayed with missing nodes. This led to me also fixing #42

2020-10-21 14:06 UTC, alongreyber approved these changes

2020-10-22 16:21 UTC, alongreyber approved these changes

2020-10-22 16:22 UTC, merged