Refresh access token
NCATS-Gamma/robokop-rewrite pull request #52
Opened 2020-10-16 14:52 UTC by maximusunc

I was able to leave the tab open over night and then came back in the morning and was able to continue using the app without getting a 'token expired' error.

Takes care of #18

2020-10-16 16:35 UTC, alongreyber requested changes

2020-10-16 16:35 UTC, alongreyber commented on src/components/header/Header.jsx
> +        console.log('Error refreshing user:', err.type);
The header has access to the Alert context provider so let's use that here.

2020-10-16 16:37 UTC, alongreyber commented
> I was able to leave the tab open over night and then came back in the morning and was able to continue using the app without getting a 'token expired' error.
> 
> Takes care of #18

You can also test it like this so you don't have to wait all night:

![Screen Shot 2020-10-16 at 12 34 20 PM](https://user-images.githubusercontent.com/1634866/96284927-49177e00-0fac-11eb-9417-f9274e77ac7f.png)

2020-10-20 16:23 UTC, maximusunc commented
Yes, while developing, I shortened the expiry time to be very short. Once I was done making code changes, I also let it sit open over night and was able to come back and everything worked without having to refresh.

2020-10-21 13:57 UTC, alongreyber requested changes
There are still two console.log statements for errors. Github won't let me annotate them but I think we should switch them to alerts since we're doing that for the rest of them in this file.

2020-10-21 14:56 UTC, alongreyber approved these changes

2020-10-21 17:27 UTC, merged